version: '3.7'
services:
  mysql:
    container_name: mysql
    tty: true
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: aqwsde123!
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    restart: unless-stopped
  redmine:
      container_name: redmine
      environment:
        REDMINE_DB_MYSQL: mysql
        REDMINE_DB_PASSWORD: aqwsde123!
      build:
        context: .
        dockerfile: Dockerfile
      tty: true
      ports:
        - "6847:3000"
      depends_on:
        - mysql
      restart: unless-stopped
